### ISSUE TITLE
Error running config for feline.nvim. module 'base46' not found

### ISSUE THREAD

**Issue by Mateus-M-Reis** [zbirenbaum/NvCustom#3]
After replacing my `custom` folder with the contents of this repo, I get the following error when opening any file:
```
Please check your config for correctness
packer.nvim: Error running config for feline.nvim: /home/mop/.config/nvim/lua/plugins/configs/statusline.lua:8: module 'base46' not found:
^Ino field package.preload['base46']
^Ino file './base46.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/base46.lua'
^Ino file '/usr/local/share/lua/5.1/base46.lua'
^Ino file '/usr/local/share/lua/5.1/base46/init.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/base46.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/base46/init.lua'
^Ino file '/home/mop/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/base46.lua'
^Ino file '/home/mop/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/base46/init.lua'
^Ino file '/home/mop/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/base46.lua'
^Ino file '/home/mop/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/base46/init.lua'
^Ino file './base46.so'
^Ino file '/usr/local/lib/lua/5.1/base46.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/base46.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
```
I've tried to edit the contents of the `utils/set_globals.lua` commenting out the `vim.g.clopboard` variable, editing `vim.g.python3_host_program` and `vim.g.python_host_program`. I've tried even commenting out the line **3** of the `chadrc.lua` file:
`require("custom.utils.set_globals")`.

I'm on Elementary OS 5.1.7 Hera based on Ubuntu 18.04.1. I've tried to install lua-basexx with no luck:
`sudo apt install lua-basexx`

I've also tried to install `luarocks` and `base64`:
```
sudo apt install luarocks
sudo luarocks install base64
```

The error is still the same. I'm new to ChadNvim as well to lua programing. I'm trying to config the editor but with many difficulties. Could some body help me?

**Comment by zbirenbaum** [comment]
This is my personal config repo so my feline config is entirely different from the defaults. It sounds like you are using parts of my config which remove the NvChad/base46 repo in favor of my own base-16 fork, and the default statusline, which uses base46. If you override the statusline config to get the colors using base-16 instead it will work.

I have no idea why siduck called it base46, it makes no sense to me since base-16 is called that because it has 16 colors. I'll have to ask what his reasoning was at some point.

Anyways the luarocks package you installed is useless here so feel free to remove it.
